apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: {{ .Values.ingress.name }}-{{ .Values.env }}
  namespace: {{ .Values.namespace }}
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}

spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.frontend.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}-{{ .Values.env }}-svc
                port:
                  number: 80
          - path: {{ .Values.ingress.backend.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.name }}-{{ .Values.env }}-svc
                port:
                  number: 3000
          - path: {{ .Values.ingress.redis.path }}
            pathType: Prefix
            backend:
              service:
                name: redis-config
                port:
                  number: 6379
          
